# Site settings
title: f3rno
description:  >-
  Personal website of Cris Mihalache (f3rno)
lang: en-US
timezone: Europe/Bucharest
icon: favicon.ico

# User settings
author: 
  name: Cris Mihalache
  username: f3rno
  email: me@f3rno.com
  avatar: '/assets/img/avatar.png'

# Url settings
url: https://f3rno.com
baseurl: ""
permalink: /:categories/:title
google_analytics: UA-88650524-2
fb_appid:

projects: false
collections:
  tips:
    output: false
  posts:
    output: true

# Markdown settings
markdown: kramdown
syntax_highlighter: rouge

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      image: /assets/img/avatar.png

# Build settings
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules 
  - bangsring.gemspec
  - CODE_OF_CONDUCT.md
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
